// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCacheLocationInfo(arg1) {
  return window['go']['main']['App']['GetCacheLocationInfo'](arg1);
}

export function GetCacheLocationsFromConfig() {
  return window['go']['main']['App']['GetCacheLocationsFromConfig']();
}

export function GetScanProgress() {
  return window['go']['main']['App']['GetScanProgress']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsScanning() {
  return window['go']['main']['App']['IsScanning']();
}

export function ScanCacheLocation(arg1, arg2, arg3) {
  return window['go']['main']['App']['ScanCacheLocation'](arg1, arg2, arg3);
}

export function ScanMultipleCacheLocations(arg1) {
  return window['go']['main']['App']['ScanMultipleCacheLocations'](arg1);
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}
