// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupFiles(arg1:string,arg2:string):Promise<string>;

export function ClassifyFileSafety(arg1:string):Promise<string>;

export function CleanupBackupsByAge(arg1:number):Promise<string>;

export function CleanupOldBackups(arg1:number):Promise<string>;

export function ConfirmDeletion(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:boolean):Promise<string>;

export function DeleteBackupSession(arg1:string):Promise<string>;

export function DeleteFilesWithBackup(arg1:string,arg2:string):Promise<string>;

export function DeleteFilesWithConfirmation(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<string>;

export function GetAvailableBackups():Promise<string>;

export function GetBackupBrowserData():Promise<string>;

export function GetBackupManifest():Promise<string>;

export function GetBackupProgress():Promise<string>;

export function GetBackupSession(arg1:string):Promise<string>;

export function GetBackupSessionDetails(arg1:string):Promise<string>;

export function GetBackupSystemStatus():Promise<string>;

export function GetCacheLocationInfo(arg1:string):Promise<string>;

export function GetCacheLocationsFromConfig():Promise<string>;

export function GetDeletionHistory():Promise<string>;

export function GetDeletionProgress(arg1:string):Promise<string>;

export function GetDeletionSystemStatus():Promise<string>;

export function GetFilesBySafetyLevel(arg1:string,arg2:string):Promise<string>;

export function GetLastScanResult():Promise<string>;

export function GetSafetyClassificationRules():Promise<string>;

export function GetSafetyClassificationSummary(arg1:string):Promise<string>;

export function GetScanProgress():Promise<string>;

export function GetSystemInfo():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function IsScanning():Promise<boolean>;

export function ListBackupSessions():Promise<string>;

export function PreviewRestoreOperation(arg1:string,arg2:string):Promise<string>;

export function RestoreFiles(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function RestoreFromBackup(arg1:string,arg2:boolean):Promise<string>;

export function RestoreFromBackupWithOptions(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<string>;

export function RestoreSession(arg1:string,arg2:boolean):Promise<string>;

export function RevealInFinder(arg1:string):Promise<string>;

export function ScanCacheLocation(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ScanMultipleCacheLocations(arg1:string):Promise<string>;

export function StopAllBackupOperations():Promise<void>;

export function StopDeletion(arg1:string):Promise<void>;

export function StopScan():Promise<void>;

export function ValidateFilesForDeletion(arg1:string,arg2:string):Promise<string>;

export function VerifyBackupIntegrity(arg1:string):Promise<string>;
