// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupFiles(arg1, arg2) {
  return window['go']['main']['App']['BackupFiles'](arg1, arg2);
}

export function ClassifyFileSafety(arg1) {
  return window['go']['main']['App']['ClassifyFileSafety'](arg1);
}

export function CleanupBackupsByAge(arg1) {
  return window['go']['main']['App']['CleanupBackupsByAge'](arg1);
}

export function CleanupOldBackups(arg1) {
  return window['go']['main']['App']['CleanupOldBackups'](arg1);
}

export function ConfirmDeletion(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ConfirmDeletion'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteBackupSession(arg1) {
  return window['go']['main']['App']['DeleteBackupSession'](arg1);
}

export function DeleteFilesWithBackup(arg1, arg2) {
  return window['go']['main']['App']['DeleteFilesWithBackup'](arg1, arg2);
}

export function DeleteFilesWithConfirmation(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteFilesWithConfirmation'](arg1, arg2, arg3, arg4);
}

export function ExportSettings(arg1) {
  return window['go']['main']['App']['ExportSettings'](arg1);
}

export function GetAvailableBackups() {
  return window['go']['main']['App']['GetAvailableBackups']();
}

export function GetBackupBrowserData() {
  return window['go']['main']['App']['GetBackupBrowserData']();
}

export function GetBackupManifest() {
  return window['go']['main']['App']['GetBackupManifest']();
}

export function GetBackupProgress() {
  return window['go']['main']['App']['GetBackupProgress']();
}

export function GetBackupSession(arg1) {
  return window['go']['main']['App']['GetBackupSession'](arg1);
}

export function GetBackupSessionDetails(arg1) {
  return window['go']['main']['App']['GetBackupSessionDetails'](arg1);
}

export function GetBackupSettings() {
  return window['go']['main']['App']['GetBackupSettings']();
}

export function GetBackupSystemStatus() {
  return window['go']['main']['App']['GetBackupSystemStatus']();
}

export function GetCacheLocationInfo(arg1) {
  return window['go']['main']['App']['GetCacheLocationInfo'](arg1);
}

export function GetCacheLocationsFromConfig() {
  return window['go']['main']['App']['GetCacheLocationsFromConfig']();
}

export function GetDeletionHistory() {
  return window['go']['main']['App']['GetDeletionHistory']();
}

export function GetDeletionProgress(arg1) {
  return window['go']['main']['App']['GetDeletionProgress'](arg1);
}

export function GetDeletionSystemStatus() {
  return window['go']['main']['App']['GetDeletionSystemStatus']();
}

export function GetFilesBySafetyLevel(arg1, arg2) {
  return window['go']['main']['App']['GetFilesBySafetyLevel'](arg1, arg2);
}

export function GetLastScanResult() {
  return window['go']['main']['App']['GetLastScanResult']();
}

export function GetPerformanceSettings() {
  return window['go']['main']['App']['GetPerformanceSettings']();
}

export function GetPrivacySettings() {
  return window['go']['main']['App']['GetPrivacySettings']();
}

export function GetSafetyClassificationRules() {
  return window['go']['main']['App']['GetSafetyClassificationRules']();
}

export function GetSafetyClassificationSummary(arg1) {
  return window['go']['main']['App']['GetSafetyClassificationSummary'](arg1);
}

export function GetSafetySettings() {
  return window['go']['main']['App']['GetSafetySettings']();
}

export function GetScanProgress() {
  return window['go']['main']['App']['GetScanProgress']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSettingsInfo() {
  return window['go']['main']['App']['GetSettingsInfo']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetUISettings() {
  return window['go']['main']['App']['GetUISettings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportSettings(arg1) {
  return window['go']['main']['App']['ImportSettings'](arg1);
}

export function IsScanning() {
  return window['go']['main']['App']['IsScanning']();
}

export function ListBackupSessions() {
  return window['go']['main']['App']['ListBackupSessions']();
}

export function PreviewRestoreOperation(arg1, arg2) {
  return window['go']['main']['App']['PreviewRestoreOperation'](arg1, arg2);
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function RestoreFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreFiles'](arg1, arg2, arg3);
}

export function RestoreFromBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreFromBackup'](arg1, arg2);
}

export function RestoreFromBackupWithOptions(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RestoreFromBackupWithOptions'](arg1, arg2, arg3, arg4);
}

export function RestoreSession(arg1, arg2) {
  return window['go']['main']['App']['RestoreSession'](arg1, arg2);
}

export function RevealInFinder(arg1) {
  return window['go']['main']['App']['RevealInFinder'](arg1);
}

export function ScanCacheLocation(arg1, arg2, arg3) {
  return window['go']['main']['App']['ScanCacheLocation'](arg1, arg2, arg3);
}

export function ScanMultipleCacheLocations(arg1) {
  return window['go']['main']['App']['ScanMultipleCacheLocations'](arg1);
}

export function StopAllBackupOperations() {
  return window['go']['main']['App']['StopAllBackupOperations']();
}

export function StopDeletion(arg1) {
  return window['go']['main']['App']['StopDeletion'](arg1);
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}

export function UpdateBackupSettings(arg1) {
  return window['go']['main']['App']['UpdateBackupSettings'](arg1);
}

export function UpdatePerformanceSettings(arg1) {
  return window['go']['main']['App']['UpdatePerformanceSettings'](arg1);
}

export function UpdatePrivacySettings(arg1) {
  return window['go']['main']['App']['UpdatePrivacySettings'](arg1);
}

export function UpdateSafetySettings(arg1) {
  return window['go']['main']['App']['UpdateSafetySettings'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateUISettings(arg1) {
  return window['go']['main']['App']['UpdateUISettings'](arg1);
}

export function ValidateFilesForDeletion(arg1, arg2) {
  return window['go']['main']['App']['ValidateFilesForDeletion'](arg1, arg2);
}

export function ValidateSettings(arg1) {
  return window['go']['main']['App']['ValidateSettings'](arg1);
}

export function VerifyBackupIntegrity(arg1) {
  return window['go']['main']['App']['VerifyBackupIntegrity'](arg1);
}
