// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClassifyFileSafety(arg1:string):Promise<string>;

export function GetCacheLocationInfo(arg1:string):Promise<string>;

export function GetCacheLocationsFromConfig():Promise<string>;

export function GetFilesBySafetyLevel(arg1:string,arg2:string):Promise<string>;

export function GetLastScanResult():Promise<string>;

export function GetSafetyClassificationRules():Promise<string>;

export function GetSafetyClassificationSummary(arg1:string):Promise<string>;

export function GetScanProgress():Promise<string>;

export function GetSystemInfo():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function IsScanning():Promise<boolean>;

export function ScanCacheLocation(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ScanMultipleCacheLocations(arg1:string):Promise<string>;

export function StopScan():Promise<void>;
